FLAGS = -pedantic-errors -std=c++11

main: welcome.cpp keyboard.cpp menu.cpp main.cpp
	g++ $(FLAGS) $^ -o $@ -lpthread

clean:


tar:


.PHONY: clean tar

# g++ -pedantic-errors -std=c++11 welcome.cpp keyboard.cpp menu.cpp main.cpp -o main.exe